name: release-blocklet

on:
  push:
    branches:
      - master
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Init
        run: pnpm i

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1.1
        with:
          skip-upload: false
          skip-deploy: false
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          deploy-app-did: zNKqftHB7ibZkHrz6Gu37xJXHLKqH5TJYEgd
          deploy-mount-point: /
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
