name: release-blocklet

on:
  push:
    branches:
      - master
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Init
        run: make github-init

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1.1
        with:
          skip-upload: false
          skip-deploy: false
          bundle-command: NODE_OPTIONS=--openssl-legacy-provider yarn bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          abtnode-endpoint: ${{ secrets.STAGING_NODE_ENDPOINT }}
          deploy-app-did: zNKqftHB7ibZkHrz6Gu37xJXHLKqH5TJYEgd
          deploy-mount-point: /
          access-key: ${{ secrets.STAGING_NODE_ACCESS_KEY }}
          access-secret: ${{ secrets.STAGING_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
